export const ScreenNames = {
  MAIN_STACK: 'MAIN_STACK',
  BOTTOM_TAB: 'BOTTOM_TAB',
  SPLASH: 'SPLASH',
  WELCOME: 'WELCOME',
  SIGN_IN: 'SIGN_IN',
  HOME: 'HOME',
  SCAN_LIST: 'SCAN_LIST',
  MY_PROFILE: 'MY_PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',
  LIST_PAGE: 'LIST_PAGE',
};
